apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synthetics-operator.fullname" . }}-webhook
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "synthetics-operator.name" . }}
      app.kubernetes.io/component: webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "synthetics-operator.name" . }}
        app.kubernetes.io/component: webhook
    spec:
      serviceAccountName: {{ include "synthetics-operator.webhookServiceAccountName" . }}
      {{- with .Values.webhook.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: webhook
          image: {{ include "synthetics-operator.componentImage" (dict "ctx" . "image" .Values.webhook.image) | quote }}
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - --webhook-port=9443
            - --webhook-namespace=$(POD_NAMESPACE)
            - --webhook-secret-name={{ .Values.webhook.secretName }}
            - --webhook-service-name={{ include "synthetics-operator.webhookServiceName" . }}
            - --validating-webhook-configuration={{ .Values.webhook.validatingWebhookConfigurationName }}
            - --mutating-webhook-configuration={{ .Values.webhook.mutatingWebhookConfigurationName }}
          ports:
            - name: webhook
              containerPort: 9443
            - name: healthz
              containerPort: 8081
            - name: metrics
              containerPort: 8082
          resources:
{{ toYaml .Values.webhook.resources | indent 12 }}
