apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synthetics-operator.fullname" . }}-controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "synthetics-operator.name" . }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "synthetics-operator.name" . }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "synthetics-operator.serviceAccountName" . }}
      containers:
        - name: controller
          image: {{ include "synthetics-operator.componentImage" (dict "image" .Values.controller.image) | quote }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - --webhook-namespace=$(POD_NAMESPACE)
            - --webhook-service-name={{ include "synthetics-operator.webhookServiceName" . }}
            - --webhook-secret-name={{ .Values.webhook.secretName }}
            - --validating-webhook-configuration={{ .Values.webhook.validatingWebhookConfigurationName }}
            - --mutating-webhook-configuration={{ .Values.webhook.mutatingWebhookConfigurationName }}
            {{- if .Values.controller.leaderElection }}
            - --leader-elect=true
            {{- end }}
            - --nats-url={{ include "synthetics-operator.natsURL" . }}
            {{- if .Values.testSidecar.image }}
            - --test-sidecar-image={{ .Values.testSidecar.image }}
            {{- end }}
            {{- if .Values.k6Runner.image }}
            - --k6-runner-image={{ .Values.k6Runner.image }}
            {{- end }}
            {{- if .Values.playwrightRunner.image }}
            - --playwright-runner-image={{ .Values.playwrightRunner.image }}
            {{- end }}
          ports:
            - name: healthz
              containerPort: 8081
            - name: metrics
              containerPort: 8082
          resources:
{{ toYaml .Values.controller.resources | indent 12 }}
