apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "synthetics-operator.fullname" . }}-webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "synthetics-operator.name" . }}
      app.kubernetes.io/component: webhook
