apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.mutatingWebhookConfigurationName }}
webhooks:
  - name: mhttpprobe.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /mutate-synthetics-dev-v1alpha1-httpprobe
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["httpprobes"]
  - name: mdnsprobe.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /mutate-synthetics-dev-v1alpha1-dnsprobe
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["dnsprobes"]
  - name: mtcpprobe.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /mutate-synthetics-dev-v1alpha1-tcpprobe
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["tcpprobes"]
  - name: mk6test.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /mutate-synthetics-dev-v1alpha1-k6test
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["k6tests"]
  - name: mplaywrighttest.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /mutate-synthetics-dev-v1alpha1-playwrighttest
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["playwrighttests"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.validatingWebhookConfigurationName }}
webhooks:
  - name: vhttpprobe.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /validate-synthetics-dev-v1alpha1-httpprobe
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["httpprobes"]
  - name: vdnsprobe.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /validate-synthetics-dev-v1alpha1-dnsprobe
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["dnsprobes"]
  - name: vtcpprobe.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /validate-synthetics-dev-v1alpha1-tcpprobe
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["tcpprobes"]
  - name: vk6test.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /validate-synthetics-dev-v1alpha1-k6test
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["k6tests"]
  - name: vplaywrighttest.kb.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "synthetics-operator.webhookServiceName" . }}
        path: /validate-synthetics-dev-v1alpha1-playwrighttest
    rules:
      - apiGroups: ["synthetics.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["playwrighttests"]
