apiVersion: v1
kind: Service
metadata:
  name: synthetics-operator-webhook-service
spec:
  selector:
    app.kubernetes.io/name: synthetics-operator
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: webhook
