image:
  ref: ""
  repository: ghcr.io/loks0n/synthetics-operator
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

serviceAccount:
  create: true
  name: ""

resources: {}

webhook:
  serviceName: synthetics-operator-webhook-service
  secretName: synthetics-webhook-certs
  validatingWebhookConfigurationName: synthetics-operator-validating-webhook-configuration
  mutatingWebhookConfigurationName: synthetics-operator-mutating-webhook-configuration
