//go:build !ignore_autogenerated

package v1alpha1

import (
	"maps"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *HTTPRequestSpec) DeepCopyInto(out *HTTPRequestSpec) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		maps.Copy(*out, *in)
	}
}

func (in *HTTPRequestSpec) DeepCopy() *HTTPRequestSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRequestSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPAssertions) DeepCopyInto(out *HTTPAssertions) {
	*out = *in
	if in.Latency != nil {
		in, out := &in.Latency, &out.Latency
		*out = new(LatencyAssertion)
		**out = **in
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(BodyAssertion)
		(*in).DeepCopyInto(*out)
	}
}

func (in *HTTPAssertions) DeepCopy() *HTTPAssertions {
	if in == nil {
		return nil
	}
	out := new(HTTPAssertions)
	in.DeepCopyInto(out)
	return out
}

func (in *LatencyAssertion) DeepCopyInto(out *LatencyAssertion) {
	*out = *in
}

func (in *LatencyAssertion) DeepCopy() *LatencyAssertion {
	if in == nil {
		return nil
	}
	out := new(LatencyAssertion)
	in.DeepCopyInto(out)
	return out
}

func (in *BodyAssertion) DeepCopyInto(out *BodyAssertion) {
	*out = *in
	if in.JSON != nil {
		in, out := &in.JSON, &out.JSON
		*out = make([]JSONAssertion, len(*in))
		copy(*out, *in)
	}
}

func (in *BodyAssertion) DeepCopy() *BodyAssertion {
	if in == nil {
		return nil
	}
	out := new(BodyAssertion)
	in.DeepCopyInto(out)
	return out
}

func (in *JSONAssertion) DeepCopyInto(out *JSONAssertion) {
	*out = *in
}

func (in *JSONAssertion) DeepCopy() *JSONAssertion {
	if in == nil {
		return nil
	}
	out := new(JSONAssertion)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbeSpec) DeepCopyInto(out *HTTPProbeSpec) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	in.Assertions.DeepCopyInto(&out.Assertions)
	out.Interval = in.Interval
	out.Timeout = in.Timeout
}

func (in *HTTPProbeSpec) DeepCopy() *HTTPProbeSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPProbeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbeStatus) DeepCopyInto(out *HTTPProbeStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessTime != nil {
		in, out := &in.LastSuccessTime, &out.LastSuccessTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailureTime != nil {
		in, out := &in.LastFailureTime, &out.LastFailureTime
		*out = (*in).DeepCopy()
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(ProbeSummary)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ProbeSummary) DeepCopyInto(out *ProbeSummary) {
	*out = *in
}

func (in *ProbeSummary) DeepCopy() *ProbeSummary {
	if in == nil {
		return nil
	}
	out := new(ProbeSummary)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbeStatus) DeepCopy() *HTTPProbeStatus {
	if in == nil {
		return nil
	}
	out := new(HTTPProbeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbe) DeepCopyInto(out *HTTPProbe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HTTPProbe) DeepCopy() *HTTPProbe {
	if in == nil {
		return nil
	}
	out := new(HTTPProbe)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HTTPProbeList) DeepCopyInto(out *HTTPProbeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HTTPProbeList) DeepCopy() *HTTPProbeList {
	if in == nil {
		return nil
	}
	out := new(HTTPProbeList)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
