//go:build !ignore_autogenerated

package v1alpha1

import (
	"maps"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *HTTPRequestSpec) DeepCopyInto(out *HTTPRequestSpec) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		maps.Copy(*out, *in)
	}
}

func (in *HTTPRequestSpec) DeepCopy() *HTTPRequestSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRequestSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbeSpec) DeepCopyInto(out *HTTPProbeSpec) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	out.Interval = in.Interval
	out.Timeout = in.Timeout
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
	if in.Assertions != nil {
		in, out := &in.Assertions, &out.Assertions
		*out = make([]Assertion, len(*in))
		copy(*out, *in)
	}
}

func (in *HTTPProbeSpec) DeepCopy() *HTTPProbeSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPProbeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbeStatus) DeepCopyInto(out *HTTPProbeStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessTime != nil {
		in, out := &in.LastSuccessTime, &out.LastSuccessTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailureTime != nil {
		in, out := &in.LastFailureTime, &out.LastFailureTime
		*out = (*in).DeepCopy()
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(ProbeSummary)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ProbeSummary) DeepCopyInto(out *ProbeSummary) {
	*out = *in
}

func (in *ProbeSummary) DeepCopy() *ProbeSummary {
	if in == nil {
		return nil
	}
	out := new(ProbeSummary)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbeStatus) DeepCopy() *HTTPProbeStatus {
	if in == nil {
		return nil
	}
	out := new(HTTPProbeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbe) DeepCopyInto(out *HTTPProbe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HTTPProbe) DeepCopy() *HTTPProbe {
	if in == nil {
		return nil
	}
	out := new(HTTPProbe)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HTTPProbeList) DeepCopyInto(out *HTTPProbeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HTTPProbeList) DeepCopy() *HTTPProbeList {
	if in == nil {
		return nil
	}
	out := new(HTTPProbeList)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPProbeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DNS types

func (in *DNSQuery) DeepCopyInto(out *DNSQuery) {
	*out = *in
}

func (in *DNSQuery) DeepCopy() *DNSQuery {
	if in == nil {
		return nil
	}
	out := new(DNSQuery)
	in.DeepCopyInto(out)
	return out
}

func (in *Assertion) DeepCopyInto(out *Assertion) {
	*out = *in
}

func (in *Assertion) DeepCopy() *Assertion {
	if in == nil {
		return nil
	}
	out := new(Assertion)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSProbeSpec) DeepCopyInto(out *DNSProbeSpec) {
	*out = *in
	out.Interval = in.Interval
	out.Timeout = in.Timeout
	out.Query = in.Query
	if in.Assertions != nil {
		in, out := &in.Assertions, &out.Assertions
		*out = make([]Assertion, len(*in))
		copy(*out, *in)
	}
}

func (in *DNSProbeSpec) DeepCopy() *DNSProbeSpec {
	if in == nil {
		return nil
	}
	out := new(DNSProbeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSProbeStatus) DeepCopyInto(out *DNSProbeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DNSProbeStatus) DeepCopy() *DNSProbeStatus {
	if in == nil {
		return nil
	}
	out := new(DNSProbeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSProbe) DeepCopyInto(out *DNSProbe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DNSProbe) DeepCopy() *DNSProbe {
	if in == nil {
		return nil
	}
	out := new(DNSProbe)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSProbe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DNSProbeList) DeepCopyInto(out *DNSProbeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DNSProbeList) DeepCopy() *DNSProbeList {
	if in == nil {
		return nil
	}
	out := new(DNSProbeList)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSProbeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
