//go:build !ignore_autogenerated

package v1alpha1

import (
	"maps"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *HTTPRequestSpec) DeepCopyInto(out *HTTPRequestSpec) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		maps.Copy(*out, *in)
	}
}

func (in *HTTPRequestSpec) DeepCopy() *HTTPRequestSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRequestSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HTTPAssertions) DeepCopyInto(out *HTTPAssertions) {
	*out = *in
}

func (in *HTTPAssertions) DeepCopy() *HTTPAssertions {
	if in == nil {
		return nil
	}
	out := new(HTTPAssertions)
	in.DeepCopyInto(out)
	return out
}

func (in *HttpProbeSpec) DeepCopyInto(out *HttpProbeSpec) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	out.Assertions = in.Assertions
	out.Interval = in.Interval
	out.Timeout = in.Timeout
}

func (in *HttpProbeSpec) DeepCopy() *HttpProbeSpec {
	if in == nil {
		return nil
	}
	out := new(HttpProbeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HttpProbeStatus) DeepCopyInto(out *HttpProbeStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessTime != nil {
		in, out := &in.LastSuccessTime, &out.LastSuccessTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailureTime != nil {
		in, out := &in.LastFailureTime, &out.LastFailureTime
		*out = (*in).DeepCopy()
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(ProbeSummary)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ProbeSummary) DeepCopyInto(out *ProbeSummary) {
	*out = *in
}

func (in *ProbeSummary) DeepCopy() *ProbeSummary {
	if in == nil {
		return nil
	}
	out := new(ProbeSummary)
	in.DeepCopyInto(out)
	return out
}

func (in *HttpProbeStatus) DeepCopy() *HttpProbeStatus {
	if in == nil {
		return nil
	}
	out := new(HttpProbeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *HttpProbe) DeepCopyInto(out *HttpProbe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HttpProbe) DeepCopy() *HttpProbe {
	if in == nil {
		return nil
	}
	out := new(HttpProbe)
	in.DeepCopyInto(out)
	return out
}

func (in *HttpProbe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HttpProbeList) DeepCopyInto(out *HttpProbeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HttpProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HttpProbeList) DeepCopy() *HttpProbeList {
	if in == nil {
		return nil
	}
	out := new(HttpProbeList)
	in.DeepCopyInto(out)
	return out
}

func (in *HttpProbeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
