{
 "title": "Synthetics / HTTP Probe",
 "tags": [
  "synthetics",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(synthetics_probe_up{kind=\"HTTPProbe\"}, namespace)"
    }
   },
   {
    "name": "url",
    "label": "URL",
    "query": "label_values(synthetics_probe_http_status_code{namespace=\"$namespace\"}, url)"
   }
  ]
 },
 "panels": [
  {
   "title": "Method",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 3, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthetics_probe_http_info{namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "URL",
   "type": "stat",
   "gridPos": { "x": 3, "y": 0, "w": 21, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthetics_probe_http_info{namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "x": 0, "y": 3, "w": 6, "h": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthetics_probe_up{kind=\"HTTPProbe\", namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "24h",
   "type": "stat",
   "gridPos": { "x": 6, "y": 3, "w": 2, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(max by(name, namespace, kind, url)(synthetics_probe_up{url=\"$url\", namespace=\"$namespace\"})[1d:30s]) * 100"
    }
   ]
  },
  {
   "title": "7d",
   "type": "stat",
   "gridPos": { "x": 8, "y": 3, "w": 2, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(max by(name, namespace, kind, url)(synthetics_probe_up{url=\"$url\", namespace=\"$namespace\"})[7d:30s]) * 100"
    }
   ]
  },
  {
   "title": "14d",
   "type": "stat",
   "gridPos": { "x": 10, "y": 3, "w": 2, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(max by(name, namespace, kind, url)(synthetics_probe_up{url=\"$url\", namespace=\"$namespace\"})[14d:30s]) * 100"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 3, "w": 4, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthetics_probe_duration_ms{kind=\"HTTPProbe\", namespace=\"$namespace\", url=\"$url\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "x": 16, "y": 3, "w": 4, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthetics_probe_tls_cert_expiry_timestamp_seconds{namespace=\"$namespace\", url=\"$url\"} - time()"
    }
   ]
  },
  {
   "title": "Last Run",
   "type": "stat",
   "gridPos": { "x": 20, "y": 3, "w": 4, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthetics_last_run_timestamp{kind=\"HTTPProbe\", namespace=\"$namespace\", url=\"$url\"} * 1000"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "state-timeline",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "synthetics_probe_http_status_code{namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Assertions",
   "type": "table",
   "gridPos": { "x": 0, "y": 15, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "synthetics_probe_assertion_result{namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{assertion}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 21, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "synthetics_probe_http_phase_duration_ms{phase=\"dns\", namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "synthetics_probe_http_phase_duration_ms{phase=\"connect\", namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "synthetics_probe_http_phase_duration_ms{phase=\"tls\", namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "synthetics_probe_http_phase_duration_ms{phase=\"processing\", namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "synthetics_probe_http_phase_duration_ms{phase=\"transfer\", namespace=\"$namespace\", url=\"$url\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "x": 0, "y": 29, "w": 24, "h": 6 } }
 ]
}